{
 "title": "Prophet",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Demo.robustperception.io",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Active_file_bytes" }
   ]
  },
  {
   "title": "ANOMALY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_file_bytes_prophet{value_type=\"anomaly\"}"
    }
   ]
  },
  {
   "title": "Prophet Local",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_file_bytes_prophet{exported_instance=\"demo.robustperception.io:9100\", exported_job=\"node\", job=\"prometheus\", value_type=\"yhat_lower\"}",
     "legendFormat": "{{ value_type }}"
    },
    {
     "expr": "node_memory_Active_file_bytes_prophet{exported_instance=\"demo.robustperception.io:9100\", exported_job=\"node\", job=\"prometheus\", value_type=\"yhat_upper\"}",
     "legendFormat": "{{ value_type }}"
    },
    {
     "expr": "node_memory_Active_file_bytes_prophet{exported_instance=\"demo.robustperception.io:9100\", exported_job=\"node\", job=\"prometheus\", value_type=\"yhat\"}",
     "legendFormat": "{{ value_type }}"
    }
   ]
  }
 ]
}